language: node_js

node_js: 
  - node

before_script:
  - npm install

services:
  - postgresql
before_script:
  - psql -c 'create database testing;' -U postgres

script:
  - npm test

after script:
  - npm run coverage

